<?php
/**
 * Created by PhpStorm.
 * User: Elendilka
 * Date: 05.06.2015
 * Time: 11:57
 */
header('Content-Type: text/html; charset=utf-8');
?>
<html>
<head>
    <title>Мой тренировочный веб-сайт по применению jQuery</title>
    <link rel="stylesheet" type="text/css" href="style/style.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
</head>


























</html>