<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Выдвижная панель</title>
    <link rel="stylesheet" type="text/css" href="style/style.css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){

            $(".btn-slide").click(function(){
                $("#panel").slideToggle("slow");
                $(this).toggleClass("active"); return false;
            });


        });
    </script>
</head>
<body>
<div id="panel">
    <!-- you can put content here -->
</div>
<p class="slide"><a href="#" class="btn-slide">Slide Panel</a></p>
</body>
</html>